### ISSUE TITLE
Name changes & alias removal

### ISSUE THREAD

**Issue by salexzee** [salexzee/Easify#26]
I will be changing some of the method names to their, easier to remember, aliases. Also, some aliases will just be removed all together. The goal is to get rid of all aliases and just have simple to remember names for all methods. You can check out the progress in this [branch](https://github.com/salexzee/Easify/tree/change-names).

**Comment by KingShimkus** [comment]
Looking good, I hope you change `contains()` to `has()`, because that is much easier to remember. So I would change the global function `contains` to `has` on [Line 427](https://github.com/salexzee/Easify/blob/change-names/src/Easify.js#L427). Also remember that you use `.contains()` on [Line 579](https://github.com/salexzee/Easify/blob/change-names/src/Easify.js#L579)  and [Line 552](https://github.com/salexzee/Easify/blob/change-names/src/Easify.js#L552), so I would change that too. And then remove the prototype on [Line 1012](https://github.com/salexzee/Easify/blob/change-names/src/Easify.js#L1012). Sorry if I am confusing you, that is the last thing I want to do. Also was wondering if there is a faster way I can talk to you?

**Comment by salexzee** [comment]
Nah it wasn't confusing. I'll probably be doing this one pretty soon. 12 hour work days slow things down sometimes.

For now direct message in my twitter @samthewebb or my email are probably the fastest ways to talk to me.

**Comment by salexzee** [comment]
`contains()` has been changed to `has()` in the branch and the other main changes, to get rid of aliases, are done and sitting in the branch. I'll merge them a little later.
